// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostPasswordHandlerFunc turns a function with the right signature into a post password handler
type PostPasswordHandlerFunc func(PostPasswordParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPasswordHandlerFunc) Handle(params PostPasswordParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostPasswordHandler interface for that can handle valid post password params
type PostPasswordHandler interface {
	Handle(PostPasswordParams, interface{}) middleware.Responder
}

// NewPostPassword creates a new http.Handler for the post password operation
func NewPostPassword(ctx *middleware.Context, handler PostPasswordHandler) *PostPassword {
	return &PostPassword{Context: ctx, Handler: handler}
}

/*PostPassword swagger:route POST /password users postPassword

change or reset an user password

*/
type PostPassword struct {
	Context *middleware.Context
	Handler PostPasswordHandler
}

func (o *PostPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostPasswordParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
