swagger: '2.0'
info:
  version: 0.0.1
  title: User Management
basePath: /v1/
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
security:
  - jwt: []

paths:
  /users:
    get:
      summary: generates a list of users
      parameters:
        - in: query
          name: offset
          type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          type: integer
          description: The numbers of items to return
        - in: query
          name: voice
          type: boolean
          description: return only users with voice activated
      responses:
        200:
          description:  full user list
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                username:
                  type: string
                created:
                  type: string
                f2a:
                  type: integer
                voice:
                  type: integer
        default:
          $ref: "#/responses/DefaultError"
  
  /user/login:
    put:
      summary: verify and parse a login token and return all user info 
      responses:
          200:
            description: the user info associated with this token
            schema:
              type: object
              properties:
                id:
                  type: integer
                username:
                  type: string
                tenant_id:
                  type: integer
                active:
                  type: boolean
                created:
                  type: string
                reset_password_next_login:
                  type: boolean
                voice:
                  type: boolean
                person_id:
                  type: integer
                  x-nullable: true
                email:
                  type: string
                f2a:
                  type: boolean
          default:
            $ref: "#/responses/DefaultError"
    post:
      security: []
      summary: generates a swt token to use for authentication
      parameters:
        - in: body
          name: body
          schema:
              $ref: "#/definitions/Login"

      responses:
        200:
          description: A jwt token to use for authentication.
          schema:
            $ref: "#/definitions/Jwt"
        206:
          description: Account is with 2 factor authenticaiton so use the 2 factor endpoint to generate the final the jwt token.
          schema:
            $ref: "#/definitions/Jwt"
        201:
          description: Password change is required, hit the password reset endpoint with the generated jwt token
          schema:
            $ref: "#/definitions/Jwt"
        202:
          description: Account is with 2fa enforcing so need to enable the 2fa
          schema:
            $ref: "#/definitions/Jwt"
        default:
          $ref: "#/responses/DefaultError"
  /user/{id}/f2a:
    parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: id of the user.
    delete:
      summary: disable 2 factor authenticaiton for an account. 
      parameters:
        - in: body
          name: body
          schema:
            $ref:
              "#/definitions/F2aDisable"
      responses:
        200:
          description: 2 factor disabled.
        401:
          $ref: "#/responses/UnauthorizedError"
        default:
          $ref: "#/responses/DefaultError"
    post:
      summary: enables 2fa on an account
      security: [] #we do additinal check in the function as otherwise can't implement the f2 enabling enforcment
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/F2aEnable"
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        401:
          $ref: "#/responses/UnauthorizedError"
        default:
          $ref: "#/responses/DefaultError"
  /user/f2a:
    get:
      summary: generates a qr base64 encoded image and master code for the user to scan with the google authenticator and add it to the phone app
      security: []
      responses:
        200:
          description: The  2fa qr image needed to be scanned by the google authenticator app. 
                      The secrets needs to be passed back to the 2fa enabling api
          schema:
            properties:
              qr:
                type: string
              secret:
                type: string
        default:
          $ref: "#/responses/DefaultError"
    
    post:
      summary: used when the account is with 2 factor authentication enabled. use the login endpoint first to get the initial jwt token and than use this endpoint to get the second jwt token after providing a valid google authenticator code
      security: []
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/F2aAuth"
      responses:
        200:
          description: the new jwt token that can be used for all endpoints.
          schema:
            $ref: "#/definitions/Jwt"
        401:
          $ref: "#/responses/UnauthorizedError"
        default:
          $ref: "#/responses/DefaultError"
  /user/:
    post:
      summary: creates a new user
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Profile"
      responses:
        200:
          description: id of the created user.
          schema:
            type: object
            properties:
              id:
                type: integer
        409:
          $ref: "#/responses/UserExistsError"
        default:
          $ref: "#/responses/DefaultError"
  /user/{id}:
    parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: id of the user.
    put:
      summary: updates an existing user, only submited fields will be updated so can ommit the ones that don't need updating
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/ProfileUpdate"
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        default:
          $ref: "#/responses/DefaultError"
    delete:
      summary: deletes a user from the db
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        default:
          $ref: "#/responses/DefaultError"

  /user/{id}/password:
    parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: id of the user
    post:
      summary: reset an user password, when old password is not provided the user will be required to change its password upon next login using a temporary password provided by an admin
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/PassReset"
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        401:
          $ref: "#/responses/UnauthorizedError"
        default:
          $ref: "#/responses/DefaultError"
    put:
      summary: resets an user password using a temporary password provided by an admin, once reset you can login as normal using the new password
      security: []
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/PassResetTemp"
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        401:
          $ref: "#/responses/UnauthorizedError"
        default:
          $ref: "#/responses/DefaultError"
  /user/roles:
    get:
      summary: generates a list of all user roles
      parameters:
        - in: query
          name: offset
          type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          type: integer
          description: The numbers of items to return
      responses:
        200:
          description:  full roles list
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                data:
                  type: string
        default:
          $ref: "#/responses/DefaultError"
  /user/role:
    post:
      summary: creates a new role
      parameters:
        - in: body
          name: body
          description: the id field here is not used so you can put any number to pass the validation
          schema:
            $ref: "#/definitions/UserRole"
      responses:
        200:
          description: the id of the created role.
          schema:
            type: object
            properties:
              id :
                type: integer
        default:
          $ref: "#/responses/DefaultError"
  /user/role/{id}:
    parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: id of the user role
    put:
      summary: updates a role
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/UserRole"
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        default:
          $ref: "#/responses/DefaultError"
    delete:
      summary: deletes a role
      responses:
        200:
          $ref: "#/responses/DefaultOk"
        default:
          $ref: "#/responses/DefaultError"
responses:
  UnauthorizedError:
    description: Authentication is missing or invalid
    schema:
      $ref: "#/definitions/Response"
  UserExistsError:
    description: Username already taken
    schema:
      $ref: "#/definitions/Response"
  DefaultError:
    description: Generic Error used for most error responses - it returns a custom code and message depending on the reply context
    schema:
      $ref: "#/definitions/Response"
  DefaultOk:
    description: Generic Ok Response - it returns a custom code and message depending on the reply context
    schema:
      $ref: "#/definitions/Response"
definitions:
  Jwt:
      type: object
      required:
      - "jwt"
      properties:
        jwt:
          type: string
  F2aAuth:
      type: object
      required:
      - jwt
      - f2a
      properties:
        jwt:
          type: string
          description: the jwt token accuired from the initial login
        f2a:
          type: string
          description: the  2 factor time code accuired from the google authenticator app
  PassReset:
      type: object
      required:
      - "password_new"
      properties:
        password_old:
          type: string
        password_new:
          type: string
  PassResetTemp:
      type: object
      required:
      - jwt
      - passwordNew
      properties:
        jwt:
          type: string
          description: the jwt token accuired form the initial login
        passwordNew:
          type: string
          description: the new password for this user
  F2aDisable:
      type: object
      required:
      - password
      properties:
        password:
          type: string
  F2aEnable:
      type: object
      required:
        - code
        - secret
      properties:
        code:
          type: string
        secret:
          type: string
      example:
            code: "the code generted by the 2 factor google android app after scanning the qr barcode"
            secret: "the master secret returned with the generated qr barcode by the api"
  Login:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
      example:
            username: "admin@mail.com"
            password: "password"
  Profile:
      type: object
      required:
      - username
      - password
      - active
      - role
      - tenant_id
      - reset_password_next_login
      properties:
        username:
          type: string
        password:
          type: string
        reset_password_next_login:
          type: boolean
        active:
          type: boolean
        email:
          type: string
        role:
          type: array
          items:
            type: integer
        tenant_id:
          type: integer
        person_id:
          type: integer
          x-nullable: true
        voice:
          type: boolean
        f2a_enforced:
          type: boolean
      example:
            username: "username"
            email: "admin@mail.com"
            password: "password"
            active: true
            voice: true
            f2a_enforced: false
            reset_password_next_login: false
            tenant_id: 1
            person_id: 1
            role:
              - 1
              - 2
  ProfileUpdate:
    type: object
    properties:
      username:
        type: string
      reset_password_next_login:
        type: string
        enum:
          - "true"
          - "false"
      f2a_enforce:
        type: string
        enum:
          - "true"
          - "false"
      password:
        type: string
      active:
        type: string
        enum:
          - "true"
          - "false"
      voice:
        type: string
        enum:
          - "true"
          - "false"
      email:
        type: string
      role:
        type: array
        items:
          type: integer
      tenant_id:
        type: integer
      person_id:
        type: integer
    example:
          username: "username"
          email: "admin@mail.com"
          password: "password"
          reset_password_next_login: "false"
          active: "true"
          voice: "true"
          f2a_enforce: "true"
          tenant_id: 1
          person_id: 1
          role:
            - 1
            - 2      
  UserRole:
      type: object
      required:
        - name
        - data
      properties:
        name:
          type: string
        data:
          type: string
      example:
          name: "admin"
          password: "{\"active\": true}"
  Response:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    example:
          code: "500"
          message: "Server error"
securityDefinitions:
   jwt:
    type: apiKey
    in: header
    name: x-jwt
