swagger: '2.0'
info:
  description: >-
    a service for user management.
  version: 0.0.1
  title: User Management
basePath: /v1/user/
tags:
  - name: users
    description: user management
schemes:
  - http
paths:
  /login:
    post:
      tags:
        - users
      summary: get an swt token to access protected endpoints
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Profile"
      responses:
        200:
          description: A token object.
          schema:
            type: object
            properties:
              token:
                type: string
        404:
          $ref: "#/responses/NotFoundError"
        default:
          $ref: "#/responses/DefaultError"

  /create:
    post:
      security:
        - swtAuth: []
      tags:
        - users
      summary: creates a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Profile"
      responses:
        200:
          description: An user id of the created user.
          schema:
            type: object
            properties:
              idProfile:
                type: string
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          $ref: "#/responses/NotFoundError"
        409:
          $ref: "#/responses/UserExistsError"
        426:
          $ref: "#/responses/ExpiredTokenError"
        default:
          $ref: "#/responses/DefaultError"

  /password:
    post:
      security:
        - swtAuth: []
      tags:
        - users
      summary: change or reset an user password
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Profile"
      responses:
        200:
          description: shows a message if the password was set or sent with an email reminder.
          schema:
            $ref: "#/definitions/Response"
        default:
          $ref: "#/responses/DefaultError"
responses:
  UnauthorizedError:
    description: SWT key is missing or invalid
    schema:
      $ref: "#/definitions/Response"
  NotFoundError:
    description: Resource not found
    schema:
      $ref: "#/definitions/Response"
  UserExistsError:
    description: Username already taken
    schema:
      $ref: "#/definitions/Response"
  ExpiredTokenError:
    description: SWT key has expired, request a new one
    schema:
      $ref: "#/definitions/Response"
  DefaultError:
    description: Unexpected error
    schema:
      $ref: "#/definitions/Response"
definitions:
  Profile:
      type: "object"
      required:
      - "email"
      - "pass"
      properties:
        email:
          type: "string"
        pass:
          type: "string"
      example:
            email: "admin@mail.com"
            pass: "password"
  Response:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
securityDefinitions:
   swtAuth:
     type: apiKey
     in: header
     name: x-token
