// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// DeleteUserManagementOKCode is the HTTP code returned for type DeleteUserManagementOK
const DeleteUserManagementOKCode int = 200

/*DeleteUserManagementOK user deleted

swagger:response deleteUserManagementOK
*/
type DeleteUserManagementOK struct {
}

// NewDeleteUserManagementOK creates DeleteUserManagementOK with default headers values
func NewDeleteUserManagementOK() *DeleteUserManagementOK {
	return &DeleteUserManagementOK{}
}

// WriteResponse to the client
func (o *DeleteUserManagementOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteUserManagementUnauthorizedCode is the HTTP code returned for type DeleteUserManagementUnauthorized
const DeleteUserManagementUnauthorizedCode int = 401

/*DeleteUserManagementUnauthorized Authentication is missing or invalid

swagger:response deleteUserManagementUnauthorized
*/
type DeleteUserManagementUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserManagementUnauthorized creates DeleteUserManagementUnauthorized with default headers values
func NewDeleteUserManagementUnauthorized() *DeleteUserManagementUnauthorized {
	return &DeleteUserManagementUnauthorized{}
}

// WithPayload adds the payload to the delete user management unauthorized response
func (o *DeleteUserManagementUnauthorized) WithPayload(payload *models.Response) *DeleteUserManagementUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user management unauthorized response
func (o *DeleteUserManagementUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserManagementUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUserManagementDefault Unexpected error

swagger:response deleteUserManagementDefault
*/
type DeleteUserManagementDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserManagementDefault creates DeleteUserManagementDefault with default headers values
func NewDeleteUserManagementDefault(code int) *DeleteUserManagementDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserManagementDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user management default response
func (o *DeleteUserManagementDefault) WithStatusCode(code int) *DeleteUserManagementDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user management default response
func (o *DeleteUserManagementDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user management default response
func (o *DeleteUserManagementDefault) WithPayload(payload *models.Response) *DeleteUserManagementDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user management default response
func (o *DeleteUserManagementDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserManagementDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
