// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// DeleteUserIDF2aOKCode is the HTTP code returned for type DeleteUserIDF2aOK
const DeleteUserIDF2aOKCode int = 200

/*DeleteUserIDF2aOK 2 factor disabled.

swagger:response deleteUserIdF2aOK
*/
type DeleteUserIDF2aOK struct {
}

// NewDeleteUserIDF2aOK creates DeleteUserIDF2aOK with default headers values
func NewDeleteUserIDF2aOK() *DeleteUserIDF2aOK {
	return &DeleteUserIDF2aOK{}
}

// WriteResponse to the client
func (o *DeleteUserIDF2aOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteUserIDF2aUnauthorizedCode is the HTTP code returned for type DeleteUserIDF2aUnauthorized
const DeleteUserIDF2aUnauthorizedCode int = 401

/*DeleteUserIDF2aUnauthorized Authentication is missing or invalid

swagger:response deleteUserIdF2aUnauthorized
*/
type DeleteUserIDF2aUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserIDF2aUnauthorized creates DeleteUserIDF2aUnauthorized with default headers values
func NewDeleteUserIDF2aUnauthorized() *DeleteUserIDF2aUnauthorized {
	return &DeleteUserIDF2aUnauthorized{}
}

// WithPayload adds the payload to the delete user Id f2a unauthorized response
func (o *DeleteUserIDF2aUnauthorized) WithPayload(payload *models.Response) *DeleteUserIDF2aUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user Id f2a unauthorized response
func (o *DeleteUserIDF2aUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserIDF2aUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUserIDF2aDefault Generic Error used for most error responses - it returns a custom code and message depending on the reply context

swagger:response deleteUserIdF2aDefault
*/
type DeleteUserIDF2aDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserIDF2aDefault creates DeleteUserIDF2aDefault with default headers values
func NewDeleteUserIDF2aDefault(code int) *DeleteUserIDF2aDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserIDF2aDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user ID f2a default response
func (o *DeleteUserIDF2aDefault) WithStatusCode(code int) *DeleteUserIDF2aDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user ID f2a default response
func (o *DeleteUserIDF2aDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user ID f2a default response
func (o *DeleteUserIDF2aDefault) WithPayload(payload *models.Response) *DeleteUserIDF2aDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user ID f2a default response
func (o *DeleteUserIDF2aDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserIDF2aDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
