// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// DeleteUserRoleOKCode is the HTTP code returned for type DeleteUserRoleOK
const DeleteUserRoleOKCode int = 200

/*DeleteUserRoleOK role deleted

swagger:response deleteUserRoleOK
*/
type DeleteUserRoleOK struct {
}

// NewDeleteUserRoleOK creates DeleteUserRoleOK with default headers values
func NewDeleteUserRoleOK() *DeleteUserRoleOK {
	return &DeleteUserRoleOK{}
}

// WriteResponse to the client
func (o *DeleteUserRoleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteUserRoleUnauthorizedCode is the HTTP code returned for type DeleteUserRoleUnauthorized
const DeleteUserRoleUnauthorizedCode int = 401

/*DeleteUserRoleUnauthorized Authentication is missing or invalid

swagger:response deleteUserRoleUnauthorized
*/
type DeleteUserRoleUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserRoleUnauthorized creates DeleteUserRoleUnauthorized with default headers values
func NewDeleteUserRoleUnauthorized() *DeleteUserRoleUnauthorized {
	return &DeleteUserRoleUnauthorized{}
}

// WithPayload adds the payload to the delete user role unauthorized response
func (o *DeleteUserRoleUnauthorized) WithPayload(payload *models.Response) *DeleteUserRoleUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user role unauthorized response
func (o *DeleteUserRoleUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserRoleUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUserRoleDefault Unexpected error

swagger:response deleteUserRoleDefault
*/
type DeleteUserRoleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserRoleDefault creates DeleteUserRoleDefault with default headers values
func NewDeleteUserRoleDefault(code int) *DeleteUserRoleDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserRoleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user role default response
func (o *DeleteUserRoleDefault) WithStatusCode(code int) *DeleteUserRoleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user role default response
func (o *DeleteUserRoleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user role default response
func (o *DeleteUserRoleDefault) WithPayload(payload *models.Response) *DeleteUserRoleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user role default response
func (o *DeleteUserRoleDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserRoleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
