// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteUserRoleIDHandlerFunc turns a function with the right signature into a delete user role ID handler
type DeleteUserRoleIDHandlerFunc func(DeleteUserRoleIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserRoleIDHandlerFunc) Handle(params DeleteUserRoleIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteUserRoleIDHandler interface for that can handle valid delete user role ID params
type DeleteUserRoleIDHandler interface {
	Handle(DeleteUserRoleIDParams, interface{}) middleware.Responder
}

// NewDeleteUserRoleID creates a new http.Handler for the delete user role ID operation
func NewDeleteUserRoleID(ctx *middleware.Context, handler DeleteUserRoleIDHandler) *DeleteUserRoleID {
	return &DeleteUserRoleID{Context: ctx, Handler: handler}
}

/*DeleteUserRoleID swagger:route DELETE /user/role/{id} deleteUserRoleId

deletes a role

*/
type DeleteUserRoleID struct {
	Context *middleware.Context
	Handler DeleteUserRoleIDHandler
}

func (o *DeleteUserRoleID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteUserRoleIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
