// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// DeleteUserRoleIDOKCode is the HTTP code returned for type DeleteUserRoleIDOK
const DeleteUserRoleIDOKCode int = 200

/*DeleteUserRoleIDOK Generic Ok Response - it returns a custom code and message depending on the reply context

swagger:response deleteUserRoleIdOK
*/
type DeleteUserRoleIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserRoleIDOK creates DeleteUserRoleIDOK with default headers values
func NewDeleteUserRoleIDOK() *DeleteUserRoleIDOK {
	return &DeleteUserRoleIDOK{}
}

// WithPayload adds the payload to the delete user role Id o k response
func (o *DeleteUserRoleIDOK) WithPayload(payload *models.Response) *DeleteUserRoleIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user role Id o k response
func (o *DeleteUserRoleIDOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserRoleIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUserRoleIDDefault Generic Error used for most error responses - it returns a custom code and message depending on the reply context

swagger:response deleteUserRoleIdDefault
*/
type DeleteUserRoleIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserRoleIDDefault creates DeleteUserRoleIDDefault with default headers values
func NewDeleteUserRoleIDDefault(code int) *DeleteUserRoleIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserRoleIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user role ID default response
func (o *DeleteUserRoleIDDefault) WithStatusCode(code int) *DeleteUserRoleIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user role ID default response
func (o *DeleteUserRoleIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user role ID default response
func (o *DeleteUserRoleIDDefault) WithPayload(payload *models.Response) *DeleteUserRoleIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user role ID default response
func (o *DeleteUserRoleIDDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserRoleIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
