// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteUserIDHandlerFunc turns a function with the right signature into a delete user ID handler
type DeleteUserIDHandlerFunc func(DeleteUserIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserIDHandlerFunc) Handle(params DeleteUserIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteUserIDHandler interface for that can handle valid delete user ID params
type DeleteUserIDHandler interface {
	Handle(DeleteUserIDParams, interface{}) middleware.Responder
}

// NewDeleteUserID creates a new http.Handler for the delete user ID operation
func NewDeleteUserID(ctx *middleware.Context, handler DeleteUserIDHandler) *DeleteUserID {
	return &DeleteUserID{Context: ctx, Handler: handler}
}

/*DeleteUserID swagger:route DELETE /user/{id} deleteUserId

deletes a user from the db

*/
type DeleteUserID struct {
	Context *middleware.Context
	Handler DeleteUserIDHandler
}

func (o *DeleteUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteUserIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
