// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/choicehealth/user-service/models"
)

// DeleteUser2faOKCode is the HTTP code returned for type DeleteUser2faOK
const DeleteUser2faOKCode int = 200

/*DeleteUser2faOK 2fa disabled.

swagger:response deleteUser2faOK
*/
type DeleteUser2faOK struct {
}

// NewDeleteUser2faOK creates DeleteUser2faOK with default headers values
func NewDeleteUser2faOK() *DeleteUser2faOK {
	return &DeleteUser2faOK{}
}

// WriteResponse to the client
func (o *DeleteUser2faOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteUser2faUnauthorizedCode is the HTTP code returned for type DeleteUser2faUnauthorized
const DeleteUser2faUnauthorizedCode int = 401

/*DeleteUser2faUnauthorized Authentication is missing or invalid

swagger:response deleteUser2faUnauthorized
*/
type DeleteUser2faUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUser2faUnauthorized creates DeleteUser2faUnauthorized with default headers values
func NewDeleteUser2faUnauthorized() *DeleteUser2faUnauthorized {
	return &DeleteUser2faUnauthorized{}
}

// WithPayload adds the payload to the delete user2fa unauthorized response
func (o *DeleteUser2faUnauthorized) WithPayload(payload *models.Response) *DeleteUser2faUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user2fa unauthorized response
func (o *DeleteUser2faUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUser2faUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUser2faDefault Unexpected error

swagger:response deleteUser2faDefault
*/
type DeleteUser2faDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUser2faDefault creates DeleteUser2faDefault with default headers values
func NewDeleteUser2faDefault(code int) *DeleteUser2faDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUser2faDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user2fa default response
func (o *DeleteUser2faDefault) WithStatusCode(code int) *DeleteUser2faDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user2fa default response
func (o *DeleteUser2faDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete user2fa default response
func (o *DeleteUser2faDefault) WithPayload(payload *models.Response) *DeleteUser2faDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user2fa default response
func (o *DeleteUser2faDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUser2faDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
