// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserIDF2aHandlerFunc turns a function with the right signature into a get user ID f2a handler
type GetUserIDF2aHandlerFunc func(GetUserIDF2aParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserIDF2aHandlerFunc) Handle(params GetUserIDF2aParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserIDF2aHandler interface for that can handle valid get user ID f2a params
type GetUserIDF2aHandler interface {
	Handle(GetUserIDF2aParams, interface{}) middleware.Responder
}

// NewGetUserIDF2a creates a new http.Handler for the get user ID f2a operation
func NewGetUserIDF2a(ctx *middleware.Context, handler GetUserIDF2aHandler) *GetUserIDF2a {
	return &GetUserIDF2a{Context: ctx, Handler: handler}
}

/*GetUserIDF2a swagger:route GET /user/{id}/f2a getUserIdF2a

enable enforcment to use 2fa on an account

*/
type GetUserIDF2a struct {
	Context *middleware.Context
	Handler GetUserIDF2aHandler
}

func (o *GetUserIDF2a) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserIDF2aParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
