// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/choicehealth/user-service/models"
)

// GetUser2faOKCode is the HTTP code returned for type GetUser2faOK
const GetUser2faOKCode int = 200

/*GetUser2faOK A 2fa object.

swagger:response getUser2faOK
*/
type GetUser2faOK struct {

	/*
	  In: Body
	*/
	Payload GetUser2faOKBody `json:"body,omitempty"`
}

// NewGetUser2faOK creates GetUser2faOK with default headers values
func NewGetUser2faOK() *GetUser2faOK {
	return &GetUser2faOK{}
}

// WithPayload adds the payload to the get user2fa o k response
func (o *GetUser2faOK) WithPayload(payload GetUser2faOKBody) *GetUser2faOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user2fa o k response
func (o *GetUser2faOK) SetPayload(payload GetUser2faOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUser2faOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUser2faUnauthorizedCode is the HTTP code returned for type GetUser2faUnauthorized
const GetUser2faUnauthorizedCode int = 401

/*GetUser2faUnauthorized Authentication is missing or invalid

swagger:response getUser2faUnauthorized
*/
type GetUser2faUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetUser2faUnauthorized creates GetUser2faUnauthorized with default headers values
func NewGetUser2faUnauthorized() *GetUser2faUnauthorized {
	return &GetUser2faUnauthorized{}
}

// WithPayload adds the payload to the get user2fa unauthorized response
func (o *GetUser2faUnauthorized) WithPayload(payload *models.Response) *GetUser2faUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user2fa unauthorized response
func (o *GetUser2faUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUser2faUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUser2faDefault Unexpected error

swagger:response getUser2faDefault
*/
type GetUser2faDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetUser2faDefault creates GetUser2faDefault with default headers values
func NewGetUser2faDefault(code int) *GetUser2faDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUser2faDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user2fa default response
func (o *GetUser2faDefault) WithStatusCode(code int) *GetUser2faDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user2fa default response
func (o *GetUser2faDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user2fa default response
func (o *GetUser2faDefault) WithPayload(payload *models.Response) *GetUser2faDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user2fa default response
func (o *GetUser2faDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUser2faDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
