// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetUser2faParams creates a new GetUser2faParams object
// with the default values initialized.
func NewGetUser2faParams() GetUser2faParams {
	var ()
	return GetUser2faParams{}
}

// GetUser2faParams contains all the bound params for the get user2fa operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUser2fa
type GetUser2faParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetUser2faParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
