// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserRoleHandlerFunc turns a function with the right signature into a get user role handler
type GetUserRoleHandlerFunc func(GetUserRoleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserRoleHandlerFunc) Handle(params GetUserRoleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUserRoleHandler interface for that can handle valid get user role params
type GetUserRoleHandler interface {
	Handle(GetUserRoleParams, interface{}) middleware.Responder
}

// NewGetUserRole creates a new http.Handler for the get user role operation
func NewGetUserRole(ctx *middleware.Context, handler GetUserRoleHandler) *GetUserRole {
	return &GetUserRole{Context: ctx, Handler: handler}
}

/*GetUserRole swagger:route GET /user/role getUserRole

generates a list of all user roles

*/
type GetUserRole struct {
	Context *middleware.Context
	Handler GetUserRoleHandler
}

func (o *GetUserRole) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserRoleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
