// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// GetUserIDF2aOKCode is the HTTP code returned for type GetUserIDF2aOK
const GetUserIDF2aOKCode int = 200

/*GetUserIDF2aOK Generic Ok Response - it returns a custom code and message depending on the reply context

swagger:response getUserIdF2aOK
*/
type GetUserIDF2aOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetUserIDF2aOK creates GetUserIDF2aOK with default headers values
func NewGetUserIDF2aOK() *GetUserIDF2aOK {
	return &GetUserIDF2aOK{}
}

// WithPayload adds the payload to the get user Id f2a o k response
func (o *GetUserIDF2aOK) WithPayload(payload *models.Response) *GetUserIDF2aOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user Id f2a o k response
func (o *GetUserIDF2aOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserIDF2aOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUserIDF2aDefault Generic Error used for most error responses - it returns a custom code and message depending on the reply context

swagger:response getUserIdF2aDefault
*/
type GetUserIDF2aDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewGetUserIDF2aDefault creates GetUserIDF2aDefault with default headers values
func NewGetUserIDF2aDefault(code int) *GetUserIDF2aDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserIDF2aDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user ID f2a default response
func (o *GetUserIDF2aDefault) WithStatusCode(code int) *GetUserIDF2aDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user ID f2a default response
func (o *GetUserIDF2aDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get user ID f2a default response
func (o *GetUserIDF2aDefault) WithPayload(payload *models.Response) *GetUserIDF2aDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user ID f2a default response
func (o *GetUserIDF2aDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserIDF2aDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
