// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// PostUserManagementHandlerFunc turns a function with the right signature into a post user management handler
type PostUserManagementHandlerFunc func(PostUserManagementParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUserManagementHandlerFunc) Handle(params PostUserManagementParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUserManagementHandler interface for that can handle valid post user management params
type PostUserManagementHandler interface {
	Handle(PostUserManagementParams, interface{}) middleware.Responder
}

// NewPostUserManagement creates a new http.Handler for the post user management operation
func NewPostUserManagement(ctx *middleware.Context, handler PostUserManagementHandler) *PostUserManagement {
	return &PostUserManagement{Context: ctx, Handler: handler}
}

/*PostUserManagement swagger:route POST /user/management postUserManagement

creates a new user

*/
type PostUserManagement struct {
	Context *middleware.Context
	Handler PostUserManagementHandler
}

func (o *PostUserManagement) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUserManagementParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostUserManagementOKBody post user management o k body
// swagger:model PostUserManagementOKBody

type PostUserManagementOKBody struct {

	// id profile
	// Required: true
	IDProfile *int64 `json:"id_profile"`
}

/* polymorph PostUserManagementOKBody id_profile false */

// Validate validates this post user management o k body
func (o *PostUserManagementOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateIDProfile(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostUserManagementOKBody) validateIDProfile(formats strfmt.Registry) error {

	if err := validate.Required("postUserManagementOK"+"."+"id_profile", "body", o.IDProfile); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostUserManagementOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostUserManagementOKBody) UnmarshalBinary(b []byte) error {
	var res PostUserManagementOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
