// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// PostUserManagementOKCode is the HTTP code returned for type PostUserManagementOK
const PostUserManagementOKCode int = 200

/*PostUserManagementOK An user id of the created user.

swagger:response postUserManagementOK
*/
type PostUserManagementOK struct {

	/*
	  In: Body
	*/
	Payload PostUserManagementOKBody `json:"body,omitempty"`
}

// NewPostUserManagementOK creates PostUserManagementOK with default headers values
func NewPostUserManagementOK() *PostUserManagementOK {
	return &PostUserManagementOK{}
}

// WithPayload adds the payload to the post user management o k response
func (o *PostUserManagementOK) WithPayload(payload PostUserManagementOKBody) *PostUserManagementOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user management o k response
func (o *PostUserManagementOK) SetPayload(payload PostUserManagementOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserManagementOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// PostUserManagementUnauthorizedCode is the HTTP code returned for type PostUserManagementUnauthorized
const PostUserManagementUnauthorizedCode int = 401

/*PostUserManagementUnauthorized Authentication is missing or invalid

swagger:response postUserManagementUnauthorized
*/
type PostUserManagementUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostUserManagementUnauthorized creates PostUserManagementUnauthorized with default headers values
func NewPostUserManagementUnauthorized() *PostUserManagementUnauthorized {
	return &PostUserManagementUnauthorized{}
}

// WithPayload adds the payload to the post user management unauthorized response
func (o *PostUserManagementUnauthorized) WithPayload(payload *models.Response) *PostUserManagementUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user management unauthorized response
func (o *PostUserManagementUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserManagementUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUserManagementConflictCode is the HTTP code returned for type PostUserManagementConflict
const PostUserManagementConflictCode int = 409

/*PostUserManagementConflict Username already taken

swagger:response postUserManagementConflict
*/
type PostUserManagementConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostUserManagementConflict creates PostUserManagementConflict with default headers values
func NewPostUserManagementConflict() *PostUserManagementConflict {
	return &PostUserManagementConflict{}
}

// WithPayload adds the payload to the post user management conflict response
func (o *PostUserManagementConflict) WithPayload(payload *models.Response) *PostUserManagementConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user management conflict response
func (o *PostUserManagementConflict) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserManagementConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostUserManagementDefault Unexpected error

swagger:response postUserManagementDefault
*/
type PostUserManagementDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostUserManagementDefault creates PostUserManagementDefault with default headers values
func NewPostUserManagementDefault(code int) *PostUserManagementDefault {
	if code <= 0 {
		code = 500
	}

	return &PostUserManagementDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post user management default response
func (o *PostUserManagementDefault) WithStatusCode(code int) *PostUserManagementDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post user management default response
func (o *PostUserManagementDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post user management default response
func (o *PostUserManagementDefault) WithPayload(payload *models.Response) *PostUserManagementDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user management default response
func (o *PostUserManagementDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserManagementDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
