// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vanderbr/choicehealth_user-service/models"
)

// PostUserIDF2aOKCode is the HTTP code returned for type PostUserIDF2aOK
const PostUserIDF2aOKCode int = 200

/*PostUserIDF2aOK Generic Ok Response - it returns a custom code and message depending on the reply context

swagger:response postUserIdF2aOK
*/
type PostUserIDF2aOK struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostUserIDF2aOK creates PostUserIDF2aOK with default headers values
func NewPostUserIDF2aOK() *PostUserIDF2aOK {
	return &PostUserIDF2aOK{}
}

// WithPayload adds the payload to the post user Id f2a o k response
func (o *PostUserIDF2aOK) WithPayload(payload *models.Response) *PostUserIDF2aOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user Id f2a o k response
func (o *PostUserIDF2aOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserIDF2aOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUserIDF2aUnauthorizedCode is the HTTP code returned for type PostUserIDF2aUnauthorized
const PostUserIDF2aUnauthorizedCode int = 401

/*PostUserIDF2aUnauthorized Authentication is missing or invalid

swagger:response postUserIdF2aUnauthorized
*/
type PostUserIDF2aUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostUserIDF2aUnauthorized creates PostUserIDF2aUnauthorized with default headers values
func NewPostUserIDF2aUnauthorized() *PostUserIDF2aUnauthorized {
	return &PostUserIDF2aUnauthorized{}
}

// WithPayload adds the payload to the post user Id f2a unauthorized response
func (o *PostUserIDF2aUnauthorized) WithPayload(payload *models.Response) *PostUserIDF2aUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user Id f2a unauthorized response
func (o *PostUserIDF2aUnauthorized) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserIDF2aUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostUserIDF2aDefault Generic Error used for most error responses - it returns a custom code and message depending on the reply context

swagger:response postUserIdF2aDefault
*/
type PostUserIDF2aDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewPostUserIDF2aDefault creates PostUserIDF2aDefault with default headers values
func NewPostUserIDF2aDefault(code int) *PostUserIDF2aDefault {
	if code <= 0 {
		code = 500
	}

	return &PostUserIDF2aDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post user ID f2a default response
func (o *PostUserIDF2aDefault) WithStatusCode(code int) *PostUserIDF2aDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post user ID f2a default response
func (o *PostUserIDF2aDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post user ID f2a default response
func (o *PostUserIDF2aDefault) WithPayload(payload *models.Response) *PostUserIDF2aDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post user ID f2a default response
func (o *PostUserIDF2aDefault) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUserIDF2aDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
