// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostUser2faHandlerFunc turns a function with the right signature into a post user2fa handler
type PostUser2faHandlerFunc func(PostUser2faParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUser2faHandlerFunc) Handle(params PostUser2faParams) middleware.Responder {
	return fn(params)
}

// PostUser2faHandler interface for that can handle valid post user2fa params
type PostUser2faHandler interface {
	Handle(PostUser2faParams) middleware.Responder
}

// NewPostUser2fa creates a new http.Handler for the post user2fa operation
func NewPostUser2fa(ctx *middleware.Context, handler PostUser2faHandler) *PostUser2fa {
	return &PostUser2fa{Context: ctx, Handler: handler}
}

/*PostUser2fa swagger:route POST /user/2fa postUser2fa

used when the account is with 2 factor authentication enabled. use the login endpoint first to get the initial jwt token and than use this endpoint to get the second jwt token after providing a valid google authenticator code

*/
type PostUser2fa struct {
	Context *middleware.Context
	Handler PostUser2faHandler
}

func (o *PostUser2fa) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUser2faParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
