// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutUserManagementHandlerFunc turns a function with the right signature into a put user management handler
type PutUserManagementHandlerFunc func(PutUserManagementParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUserManagementHandlerFunc) Handle(params PutUserManagementParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutUserManagementHandler interface for that can handle valid put user management params
type PutUserManagementHandler interface {
	Handle(PutUserManagementParams, interface{}) middleware.Responder
}

// NewPutUserManagement creates a new http.Handler for the put user management operation
func NewPutUserManagement(ctx *middleware.Context, handler PutUserManagementHandler) *PutUserManagement {
	return &PutUserManagement{Context: ctx, Handler: handler}
}

/*PutUserManagement swagger:route PUT /user/management putUserManagement

updates an existing user, only submited fields will be updated so can ommit the ones that don't need updating

*/
type PutUserManagement struct {
	Context *middleware.Context
	Handler PutUserManagementHandler
}

func (o *PutUserManagement) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutUserManagementParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
