// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutUserIDPasswordHandlerFunc turns a function with the right signature into a put user ID password handler
type PutUserIDPasswordHandlerFunc func(PutUserIDPasswordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUserIDPasswordHandlerFunc) Handle(params PutUserIDPasswordParams) middleware.Responder {
	return fn(params)
}

// PutUserIDPasswordHandler interface for that can handle valid put user ID password params
type PutUserIDPasswordHandler interface {
	Handle(PutUserIDPasswordParams) middleware.Responder
}

// NewPutUserIDPassword creates a new http.Handler for the put user ID password operation
func NewPutUserIDPassword(ctx *middleware.Context, handler PutUserIDPasswordHandler) *PutUserIDPassword {
	return &PutUserIDPassword{Context: ctx, Handler: handler}
}

/*PutUserIDPassword swagger:route PUT /user/{id}/password putUserIdPassword

resets an user password using a temporary password provided by an admin, once reset you can login as normal using the new password

*/
type PutUserIDPassword struct {
	Context *middleware.Context
	Handler PutUserIDPasswordHandler
}

func (o *PutUserIDPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutUserIDPasswordParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
