// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutUserLoginHandlerFunc turns a function with the right signature into a put user login handler
type PutUserLoginHandlerFunc func(PutUserLoginParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUserLoginHandlerFunc) Handle(params PutUserLoginParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutUserLoginHandler interface for that can handle valid put user login params
type PutUserLoginHandler interface {
	Handle(PutUserLoginParams, interface{}) middleware.Responder
}

// NewPutUserLogin creates a new http.Handler for the put user login operation
func NewPutUserLogin(ctx *middleware.Context, handler PutUserLoginHandler) *PutUserLogin {
	return &PutUserLogin{Context: ctx, Handler: handler}
}

/*PutUserLogin swagger:route PUT /user/login putUserLogin

verify and parse a login token and return all user info

*/
type PutUserLogin struct {
	Context *middleware.Context
	Handler PutUserLoginHandler
}

func (o *PutUserLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutUserLoginParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
