// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/rsa"
	"crypto/tls"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/dgrijalva/jwt-go"
	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/rs/cors"
	graceful "github.com/tylerb/graceful"
	"golang.org/x/crypto/bcrypt"

	"github.com/choicehealth/user-service/restapi/operations"
	"github.com/choicehealth/user-service/restapi/operations/users"

	"database/sql"

	_ "github.com/lib/pq"
)

var (
	verifyKey *rsa.PublicKey
	signKey   *rsa.PrivateKey
	db        *sql.DB
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name  --spec ../swagger.yaml
var keysPaths = struct {
	Pub  string `long:"pub" description:"public key path for the swt token generation" default:"/tmp/app.rsa.pub"`
	Priv string `long:"priv" description:"private key path for the swt token verification" default:"/tmp/app.rsa"`
}{}

func configureFlags(api *operations.UserManagementAPI) {
	api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{
		swag.CommandLineOptionsGroup{
			ShortDescription: "private pub key paths",
			Options:          &keysPaths,
		},
	}

}

func configureAPI(api *operations.UserManagementAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	// Applies when the "x-token" header is set
	api.SwtAuthAuth = func(token string) (interface{}, error) {
		t, err := jwt.Parse(token, func(token *jwt.Token) (interface{}, error) {
			// since we only use the one private key to sign the tokens,
			// we also only use its public counter part to verify
			log.Println(verifyKey)
			return verifyKey, nil
		})
		// branch out into the possible error from signing
		switch err.(type) {

		case nil: // no error

			if !t.Valid { // but may still be invalid
				log.Println("invalid")

				return nil, nil
			}
			log.Println("valid")

		case *jwt.ValidationError: // something was wrong during the validation
			vErr := err.(*jwt.ValidationError)

			switch vErr.Errors {
			case jwt.ValidationErrorExpired:
				log.Println("Token Expired, get a new one.")

			default:
				log.Printf("ValidationError error: %+v\n", vErr.Errors)

			}

		default: // something else went wrong
			log.Printf("Token parse error: %v\n", err)
		}
		// log.Println(t.Raw)
		return nil, nil
	}

	api.UsersPostCreateHandler = users.PostCreateHandlerFunc(func(params users.PostCreateParams, principal interface{}) middleware.Responder {

		return users.NewPostCreateOK()
	})

	api.UsersPostLoginHandler = users.PostLoginHandlerFunc(func(params users.PostLoginParams) middleware.Responder {
		rows, err := db.Query("SELECT id,user_type_id,password FROM public.user WHERE username=$1", params.Body.Email)
		if err != nil {
			log.Println(err)
			return users.NewPostLoginDefault(0)
		}
		defer rows.Close()

		for rows.Next() {
			var id int
			var user_type_id int
			var password string
			rows.Scan(&id, &user_type_id, &password)
			if bcrypt.CompareHashAndPassword([]byte(password), []byte(*params.Body.Pass)) == nil {
				t := jwt.MapClaims{
					"exp":   time.Now().Add(time.Hour * 72).Unix(),
					"scope": "browse",
				}
				switch user_type_id {
				case 1: //admin
					t["scope"] = t["scope"].(string) + ",create"
				}

				token := jwt.NewWithClaims(jwt.SigningMethodRS256, t)
				tt, err := token.SignedString(signKey)
				if err != nil {
					return users.NewPostLoginDefault(0)
				}
				return users.NewPostLoginOK().WithPayload(users.PostLoginOKBody{Token: swag.String(tt)})
			}
		}
		return users.NewPostLoginNotFound()
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {

	if key, err := ioutil.ReadFile(keysPaths.Priv); err != nil {
		log.Fatalf("can't read public file:%v", err)
	} else {
		signKey, err = jwt.ParseRSAPrivateKeyFromPEM(key)
		if err != nil {
			log.Fatalf("error parsing the  private key :%v", err)
		}
	}
	if key, err := ioutil.ReadFile(keysPaths.Pub); err != nil {
		log.Fatalf("can't read private file:%v", err)

	} else {
		verifyKey, err = jwt.ParseRSAPublicKeyFromPEM(key)
		if err != nil {
			log.Fatalf("error parsing the  public key :%v", err)
		}
	}

	if d, err := sql.Open("postgres", "postgres://"+os.Getenv("DB_USER")+":"+os.Getenv("DB_PASS")+"@"+os.Getenv("DB_HOST")+"/choicehealth?sslmode=disable"); err != nil {
		log.Fatalf("error connecting to the DB :%v", err)
	} else {
		db = d
	}
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	corsHandler := cors.New(cors.Options{
		Debug:          false,
		AllowedHeaders: []string{"*"},
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{},
		MaxAge:         1000,
	})
	return corsHandler.Handler(handler)
}
