// Code generated by go-swagger; DO NOT EDIT.

/*Package restapi User Management

a service for user management.


    Schemes:
      http
    Host: localhost:8080
    BasePath: /v1/account/
    Version: 0.0.1

    Consumes:
    - application/json


    Produces:
    - application/json


swagger:meta
*/
package restapi
