// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "a service for user management.",
    "title": "User Management",
    "version": "0.0.1"
  },
  "basePath": "/v1/user/",
  "paths": {
    "/create": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "creates a new user",
        "security": [
          {
            "swtAuth": []
          }
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "An user id of the created user.",
            "schema": {
              "type": "object",
              "properties": {
                "idProfile": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "$ref": "#/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/responses/NotFoundError"
          },
          "409": {
            "$ref": "#/responses/UserExistsError"
          },
          "426": {
            "$ref": "#/responses/ExpiredTokenError"
          },
          "default": {
            "$ref": "#/responses/DefaultError"
          }
        }
      }
    },
    "/login": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "get an swt token to access protected endpoints",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A token object.",
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "$ref": "#/responses/NotFoundError"
          },
          "default": {
            "$ref": "#/responses/DefaultError"
          }
        }
      }
    },
    "/password": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "users"
        ],
        "summary": "change or reset an user password",
        "security": [
          {
            "swtAuth": []
          }
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "shows a message if the password was set or sent with an email reminder.",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "$ref": "#/responses/DefaultError"
          }
        }
      }
    }
  },
  "definitions": {
    "Profile": {
      "type": "object",
      "required": [
        "email",
        "pass"
      ],
      "properties": {
        "email": {
          "type": "string"
        },
        "pass": {
          "type": "string"
        }
      }
    },
    "Response": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "DefaultError": {
      "description": "Unexpected error",
      "schema": {
        "$ref": "#/definitions/Response"
      }
    },
    "ExpiredTokenError": {
      "description": "SWT key has expired, request a new one",
      "schema": {
        "$ref": "#/definitions/Response"
      }
    },
    "NotFoundError": {
      "description": "Resource not found",
      "schema": {
        "$ref": "#/definitions/Response"
      }
    },
    "UnauthorizedError": {
      "description": "SWT key is missing or invalid",
      "schema": {
        "$ref": "#/definitions/Response"
      }
    },
    "UserExistsError": {
      "description": "Username already taken",
      "schema": {
        "$ref": "#/definitions/Response"
      }
    }
  },
  "securityDefinitions": {
    "swtAuth": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    }
  },
  "tags": [
    {
      "description": "user management",
      "name": "users"
    }
  ]
}`))
}
