// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProfileCreate profile create
// swagger:model ProfileCreate
type ProfileCreate struct {

	// active
	// Required: true
	Active *bool `json:"active"`

	// email
	Email string `json:"email,omitempty"`

	// password
	// Required: true
	Password *string `json:"password"`

	// role
	// Required: true
	Role []int64 `json:"role"`

	// tenant id
	// Required: true
	TenantID *int64 `json:"tenant_id"`

	// username
	// Required: true
	Username *string `json:"username"`
}

// Validate validates this profile create
func (m *ProfileCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActive(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTenantID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProfileCreate) validateActive(formats strfmt.Registry) error {

	if err := validate.Required("active", "body", m.Active); err != nil {
		return err
	}

	return nil
}

func (m *ProfileCreate) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *ProfileCreate) validateRole(formats strfmt.Registry) error {

	return nil
}

var profileCreateTypeTenantIDPropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[1]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		profileCreateTypeTenantIDPropEnum = append(profileCreateTypeTenantIDPropEnum, v)
	}
}

// prop value enum
func (m *ProfileCreate) validateTenantIDEnum(path, location string, value int64) error {
	if err := validate.Enum(path, location, value, profileCreateTypeTenantIDPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ProfileCreate) validateTenantID(formats strfmt.Registry) error {

	if err := validate.Required("tenant_id", "body", m.TenantID); err != nil {
		return err
	}

	// value enum
	if err := m.validateTenantIDEnum("tenant_id", "body", *m.TenantID); err != nil {
		return err
	}

	return nil
}

func (m *ProfileCreate) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProfileCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProfileCreate) UnmarshalBinary(b []byte) error {
	var res ProfileCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
